// File generated by FlutterFire CLI.
// ignore_for_file: type=lint


import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDda1RdHEN2EpdJpnJSP7Ph_Ewkk7xhv98',
    appId: '1:562291981418:web:a542f4c6240158116a5e13',
    messagingSenderId: '562291981418',
    projectId: 'flutter-author-reader-app',
    authDomain: 'flutter-author-reader-app.firebaseapp.com',
    databaseURL: 'https://flutter-author-reader-app-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-author-reader-app.firebasestorage.app',
    measurementId: 'G-0RQEZXB13W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf3en-TikHMBp5X0y3uTTrhCqIWXbHeHI',
    appId: '1:562291981418:android:049fc9730d71d2e36a5e13',
    messagingSenderId: '562291981418',
    projectId: 'flutter-author-reader-app',
    databaseURL: 'https://flutter-author-reader-app-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-author-reader-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfK5cbCjwwb1V95zK_R4uh76_KxcbWcAI',
    appId: '1:562291981418:ios:a5e060a1138ec1a76a5e13',
    messagingSenderId: '562291981418',
    projectId: 'flutter-author-reader-app',
    databaseURL: 'https://flutter-author-reader-app-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-author-reader-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthorReaderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfK5cbCjwwb1V95zK_R4uh76_KxcbWcAI',
    appId: '1:562291981418:ios:a5e060a1138ec1a76a5e13',
    messagingSenderId: '562291981418',
    projectId: 'flutter-author-reader-app',
    databaseURL: 'https://flutter-author-reader-app-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-author-reader-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthorReaderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDda1RdHEN2EpdJpnJSP7Ph_Ewkk7xhv98',
    appId: '1:562291981418:web:2190f62d724e6bbf6a5e13',
    messagingSenderId: '562291981418',
    projectId: 'flutter-author-reader-app',
    authDomain: 'flutter-author-reader-app.firebaseapp.com',
    databaseURL: 'https://flutter-author-reader-app-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-author-reader-app.firebasestorage.app',
    measurementId: 'G-3WJHV9WZ2X',
  );
}
